### ISSUE TITLE
NA X-axis Label

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_weather_warehouse#26]
get rid of label, it's already intuitive

**Comment by samsoe** [comment]
try minor axis formatting on 'scale_x_continuous'

**Comment by samsoe** [comment]
The NA at the beginning of January is a challenge I have not been able to address.  Fresh eyes would be good.

**Comment by bglarkin** [comment]
@samsoe The NA is because a continuous scale always includes a zero, but the zero can't be formatted to a date format. Getting rid of the zero is hard. I'm working on it. It might be something awful like an if() statement.

**Comment by bglarkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix NA axis issue in weather app](https://trello.com/c/mTHJlOkR/244-fix-na-axis-issue-in-weather-app)

**Comment by bglarkin** [comment]
`scale_x_continuous()` by default includes zero if zero is near the range being displayed. I was a little wrong about the difficulty of changing this in my earlier comment. The fix is actually simple, just a case of adding 1 to x so that there isn't a zero. But this moves the problem to the other end of the axis, so setting `limits` is necessary. 

This corrects the plot, but I need to make sure that this doesn't affect the downloadable data (it doesn't. the plot code is downstream of the filtering step that produces the data table). 

Ah, we also have leap years. In some cases, we have 366 days. 

- [x] try changing slider max to 366 and see what breaks

The correct arguments to `scale_x_continuous()` are: `scale_x_continuous(labels = function(x) format(as.Date(as.character(x+1), "%j"), "%b-%d"), 
                       limits = function(x) c(min(x)+1, max(x)-1))`

This will need to be updated in:

- [ ] temperature
- [ ] precipitation
- [ ] wind speed
- [ ] wind direction

A reference location for one plot is attached here:
https://github.com/samsoe/mpg_weather_warehouse/blob/5ede7d18cd0902b9219b27f7158182a173dfef1f/weather.Rmd#L105

**Comment by bglarkin** [comment]
Also there is a spot with cleanup needed. `group_by()` is followed immediately by `ungroup()`. Probably a remnant of earlier code. @esamsoe would you agree? Safe to delete?

- [x] clean this code
- [x] check other plot functions for this mistake and correct it

https://github.com/samsoe/mpg_weather_warehouse/blob/7b210078bc627033509d26d2fbc8c86faa07ddb7/weather.Rmd#L100-L101

**Comment by samsoe** [comment]
> Also there is a spot with cleanup needed. `group_by()` is followed immediately by `ungroup()`. Probably a remnant of earlier code. @esamsoe would you agree? Safe to delete?
> 
> * [ ]  clean this code
> * [ ]  check other plot functions for this mistake and correct it
> 
> https://github.com/samsoe/mpg_weather_warehouse/blob/7b210078bc627033509d26d2fbc8c86faa07ddb7/weather.Rmd#L100-L101

Good catch.  I agree.  Safe to delete.

**Comment by bglarkin** [comment]
> `scale_x_continuous()` by default includes zero if zero is near the range being displayed. I was a little wrong about the difficulty of changing this in my earlier comment. The fix is actually simple, just a case of adding 1 to x so that there isn't a zero. But this moves the problem to the other end of the axis, so setting `limits` is necessary.
> 
> This corrects the plot, but I need to make sure that this doesn't affect the downloadable data (it doesn't. the plot code is downstream of the filtering step that produces the data table).
> 
> Ah, we also have leap years. In some cases, we have 366 days.
> 
> * [x]  try changing slider max to 366 and see what breaks
> 
> The correct arguments to `scale_x_continuous()` are: `scale_x_continuous(labels = function(x) format(as.Date(as.character(x+1), "%j"), "%b-%d"), limits = function(x) c(min(x)+1, max(x)-1))`
> 
> This will need to be updated in:
> 
> * [ ]  temperature
> * [ ]  precipitation
> * [ ]  wind speed
> * [ ]  wind direction
> 
> A reference location for one plot is attached here:
> https://github.com/samsoe/mpg_weather_warehouse/blob/5ede7d18cd0902b9219b27f7158182a173dfef1f/weather.Rmd#L105

Will create new issue for the leap years issue

**Comment by bglarkin** [comment]
Dammit of course then I just found this and makes me wonder if I should use it instead: https://stackoverflow.com/questions/29974535/dates-with-month-and-day-in-time-series-plot-in-ggplot2-with-facet-for-years
