### ISSUE TITLE
Assign Color to each station

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_weather_warehouse#57]
Stations need sticky colors so that they are the same no matter which stations are chosen. This will be best accomplished by creating a static data frame which assigns colors to stations. Should be addressed in the opt-speed-theme branch.

**Comment by bglarkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Weather app sprint: UX issues](https://trello.com/c/cJDZoCH3/249-weather-app-sprint-ux-issues)

**Comment by bglarkin** [comment]
I chose the colorspace palette "Batlow" because it seems to separate well in six colors. It is also colorblind friendly AFAIK. The palette can easily be changed by editing one line of code: https://github.com/samsoe/mpg_weather_warehouse/blob/72c860eade98ec811ca6fd6815bff55a86eb9ffb/weather.Rmd#L25

The new colors will be assigned programmatically to stations. 

Any of the sequential palettes can be used, and others are also possible. See CRAN's [colorspace page](https://cran.r-project.org/web/packages/colorspace/vignettes/colorspace.html) for more information.
